blank_issues_enabled: true
contact_links:
    - name: 🖊️ Typo Collection Thread
      url: https://github.com/Lurkars/gloomhavensecretariat/issues/242
      about: If you just find typos, please report them in this issue!
    - name: ❓ FAQ and Basic User Guide
      url: https://help.gloomhaven-secretariat.de/
      about: A Small FAQ and basic guide how to use Gloomhaven Secretariat
    - name: 💡 General Ideas, Feedback and Questions
      url: https://github.com/Lurkars/gloomhavensecretariat/discussions
      about: To discuss ideas, give general feedback or asking for help just use the GitHub Discussion